# Generated by Django 3.0.7 on 2020-07-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_book_bookimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookPdf',
            field=models.FileField(blank=True, default='default.pdf', upload_to=''),
        ),
    ]
